# Copyright 2014 by Cloudsoft Corporation Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

language: java
jdk:
- openjdk7
script: mvn clean install
deploy:
  matrix:
  - provider: releases
    api-key: 5fb30cf15ffadb958e14cec37318cdaa19348a2f
    file: examples/target/brooklyn-clocker-dist.tar.gz
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
  - provider: s3
    access_key_id: AKIAJL5SMCB2JZCJ2WAQ
    secret_access_key:
      secure: JdnmzeTNcG52cKVx12tn05ojgPxwZ4bAdkYbSV/Uy863COhpx3glz1CakUEoDLLo606jGQuYbOiiL9KQrAJCsQe+xLsBA7NRcAoZjxhotYURdRSDYoOzeFHVWTngDOBJQ/irKzH6lYEnDowdV+lG/eAeDSD9eyo5EoEfFjFQR/I=
    skip_cleanup: true
    bucket: clocker-builds
    acl: public_read
    region: eu-west-1
    file: examples/target/brooklyn-clocker-dist.tar.gz
notifications:
  email:
  - andrew.kennedy@cloudsoft.io
  - andrea.turli@cloudsoft.io
